#file = open("new file","w")
#file.close()


#file = open("C:/Yazılım/2.) Python/1.) Dosyalama İşlemleri/Deneme Dosya/new file.txt","w")
#print(file)


# file = open("new file","w",encoding="UTF-8")
# file.write("Özgür Çet")
# file.close()

# file = open("text.txt","a",encoding="UTF-8")
# file.write(("Merhaba"+"\n"))
# file.close()



file = open("new file2.txt","x",encoding="UTF-8")
file.close()

# ==> Uygulama tekrar çalıştırılırsa dosya mevcut olduğu için, python  "x" modunda hata verecektir.











